CREATE TABLE Account(
   user_id BIGINT PRIMARY KEY,
   timezone VARCHAR(40)
);

CREATE TABLE Reminder(
   reminder_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   r_name VARCHAR(50) NOT NULL,
   r_message VARCHAR(1024) NOT NULL,
   r_time TIME NOT NULL,
   r_date DATE DEFAULT CURRENT_DATE,
   r_intervals VARCHAR(30),
   is_active BOOLEAN DEFAULT TRUE,
   user_id BIGINT NOT NULL,
   CONSTRAINT reminder_name_unique UNIQUE(user_id, reminder_name), -- A user cannot create two reminder with the same name
   CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES Account(user_id)
);
